const express = require("express");
const router = express.Router();
const { addUser, auth } = require("./auth");
const { getBooks } = require("./load");
const { sendComment } = require("./load");
router.route("/auth/signup").post(addUser);
router.route("/auth/login").post(auth);
router.route("/load/books").get(getBooks);
router.route("/load/sendcomment").post(getBooks);
module.exports = router;